updt: inline and minify html

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -12,25 +12,45 @@ jobs:
       - uses: actions/checkout@v4
       - name: Install packages
         run: |
-          sudo apt-get install nodejs npm
+          sudo apt-get update
+          sudo apt-get upgrade
+          sudo apt-get install -y nodejs npm imagemagick
           npm install
       - name: Generate caching artifacts
         run: |
           npx http-server src -p 8000 &
           node src/takeScreenshot.cjs
-      - name: Prerender HTML
+          convert -append part*.png screenshot_old.png
+          rm -rf part*.png
+      - name: Prerender and minify HTML
         run: |
           node src/fillContent.js > src/index2.html
-          mv src/index2.html src/index.html
+          pushd src
+          node postprocess.cjs > index.html
+          popd
+      - name: Generate and compare screenshot
+        run: |
+          node src/takeScreenshot.cjs nocache
+          convert -append part*.png screenshot_new.png
+          rm -rf part*.png
+          result=$(compare -metric RMSE screenshot_old.png screenshot_new.png diff.png)
+          echo "Difference: $result"
+          if [ "$result" -ne '0 (0)' ]; then
+            echo "Images do not match! Failing the job."
+            exit 1
+          fi
       - name: Remove unused files
         run: |
           rm src/.prettierrc
           rm src/input.css
+          rm src/output.css
           rm -rf src/data
+          rm -rf src/font
           rm src/fillContent.js
           rm src/resources.js
           rm src/generateLatex.js
           rm src/takeScreenshot.cjs
+          rm src/postprocess.js
       - uses: azure/login@v1
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
